import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/stories/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      mobile: { max: '640px' },
    },
    extend: {
      colors: {
        transparent: 'transparent',
        primary: '#B79D96',
        bg_white: '#FFF',
        bg_disabled: '#EEE',
        stroke_focused: '#E59888',
        gray: '#c9c8d3',
        orange: '#ff7b27',
        stroke_grey: '#BDBCDB',
        text_primary: '#333',
        text_white: '#FFF',
        text_grey: '#818181',
        text_light_grey: '#D9D9D9',
        text_validation: '#FFB82E',
        text_error: '#F93232',
        text_success: '#439F6E',
        button_bg_default: '#F6D3C9',
        button_text_default: '#FFF',
        button_bg_clicked: '#B79D96',
        button_text_clicked: '#FFF',
        button_bg_disabled: '#C8C8C8',
        button_text_disabled: '#E0E0E1',
        button_secondary_stroke: '#EFD2CA',
        button_secondary_text: '#EFD2CA',
        fields_form: '#F5F6F6',
        fields_title: '#4A4A4A',
        fields_text: '#212121',
        fields_description: '#AAA',
        fields_disabled: '#FFF',
        fields_text_disabled: '#A5A5A7',
        fields_stroke_validation: '#FFEAC1',
        fields_bg_validation: '#FFFBF4',
        fields_stroke_loading: '#E8E6F8',
        fields_bg_error: '#FFF5F5',
        fields_stroke_error: '#FFD8D8',
      },
      margin: {
        6: '6px',
        8: '8px',
        12: '12px',
        14: '14px',
        16: '16px',
        20: '20px',
        24: '24px',
        32: '32px',
        40: '40px',
        48: '48px',
        56: '56px',
        64: '64px',
        80: '80px',
        120: '120px',
      },
      padding: {
        6: '6px',
        8: '8px',
        12: '12px',
        14: '14px',
        16: '16px',
        20: '20px',
        24: '24px',
        32: '32px',
        40: '40px',
        48: '48px',
        56: '56px',
        64: '64px',
        80: '80px',
        120: '120px',
      },
      spacing: {
        6: '6px',
        8: '8px',
        12: '12px',
        14: '14px',
        16: '16px',
        20: '20px',
        24: '24px',
        32: '32px',
        40: '40px',
        48: '48px',
        56: '56px',
        64: '64px',
        80: '80px',
        120: '120px',
      },
      fontSize: {
        12: '12px',
        14: '14px',
        16: '16px',
        18: '18px',
        20: '20px',
        24: '24px',
      },
    },
  },
  plugins: [],
};

export default config;
